// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:beatfy/data/local/hive/playback_state_cache.dart';
import 'package:beatfy/models/app_preferences.dart';
import 'package:beatfy/models/cloud_backup_meta.dart';
import 'package:beatfy/models/cloud_backup_record.dart';
import 'package:beatfy/models/favorite.dart';
import 'package:beatfy/models/play_stats.dart';
import 'package:beatfy/models/playlist.dart';
import 'package:beatfy/models/song.dart';
import 'package:beatfy/models/user_profile.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppPreferencesAdapter());
    registerAdapter(BackupStatusAdapter());
    registerAdapter(CloudBackupMetaAdapter());
    registerAdapter(CloudBackupRecordAdapter());
    registerAdapter(FavoriteAdapter());
    registerAdapter(PlayStatsAdapter());
    registerAdapter(PlaybackStateCacheAdapter());
    registerAdapter(PlaylistAdapter());
    registerAdapter(RepeatModeAdapter());
    registerAdapter(SongAdapter());
    registerAdapter(SongSourceAdapter());
    registerAdapter(UserProfileCacheAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppPreferencesAdapter());
    registerAdapter(BackupStatusAdapter());
    registerAdapter(CloudBackupMetaAdapter());
    registerAdapter(CloudBackupRecordAdapter());
    registerAdapter(FavoriteAdapter());
    registerAdapter(PlayStatsAdapter());
    registerAdapter(PlaybackStateCacheAdapter());
    registerAdapter(PlaylistAdapter());
    registerAdapter(RepeatModeAdapter());
    registerAdapter(SongAdapter());
    registerAdapter(SongSourceAdapter());
    registerAdapter(UserProfileCacheAdapter());
  }
}
